esphome:
  name: slimmelezer
  friendly_name: SlimmeLezer+
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: d1_mini
external_components:
  - source: github://cyberbeni/esphome-dsmr-hu@v1
    components: [dsmr]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_slimmelezer
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet

logger:
  baud_rate: 0
api:
ota:
  platform: esphome

web_server:
  port: 80

uart:
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 3000

dsmr:
  id: dsmr_instance
  crc_check: false
  max_telegram_length: 3000

sensor:
  - platform: dsmr
    energy_delivered_lux:
      name: "Energy Consumed"
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
    energy_delivered_tariff3:
      name: "Energy Consumed Tariff 3"
    energy_delivered_tariff4:
      name: "Energy Consumed Tariff 4"
    energy_returned_lux:
      name: "Energy Produced"
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
    energy_returned_tariff3:
      name: "Energy Produced Tariff 3"
    energy_returned_tariff4:
      name: "Energy Produced Tariff 4"
    power_delivered:
      name: "Power Consumed"
    power_returned:
      name: "Power Produced"
    voltage_l1:
      name: "Voltage Phase 1"
    voltage_l2:
      name: "Voltage Phase 2"
    voltage_l3:
      name: "Voltage Phase 3"
    current_l1:
      name: "Current Phase 1"
    current_l2:
      name: "Current Phase 2"
    current_l3:
      name: "Current Phase 3"
    frequency:
      name: "Frequency"
    electricity_tariff:
      name: "Current Tariff"
  - platform: uptime
    name: "SlimmeLezer Uptime"
  - platform: wifi_signal
    name: "SlimmeLezer Wi-Fi Signal"
    update_interval: 60s

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    breaker_status: 
      name: "Breaker status"
  - platform: wifi_info
    ip_address:
      name: "SlimmeLezer IP Address"
    ssid:
      name: "SlimmeLezer Wi-Fi SSID"
    bssid:
      name: "SlimmeLezer Wi-Fi BSSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
